### ISSUE TITLE
Support did_you_mean

### ISSUE THREAD

**Issue by sue445** [sue445/rubicure#147]
# Current
```ruby
> Cure.makaron
NoMethodError: undefined method `makaron' for Cure:Module
	from /Users/sueyoshi_go/workspace/github.com/sue445/rubicure/lib/rubicure/cure.rb:6:in `method_missing'
	from (irb):1
	from /Users/sueyoshi_go/.rbenv/versions/2.4.1/bin/irb:11:in `<top (required)>'
	from /Users/sueyoshi_go/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
	from /Users/sueyoshi_go/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /Users/sueyoshi_go/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
```

# Expected 
```ruby
> Cure.makaron
NoMethodError: undefined method `makaron' for Cure:Module
Did you mean? macaroon
```

**Comment by sue445** [comment]
Resolved at #150
